TARGETS = bubbleSort heapSort heapSortVariant

all: $(TARGETS)

bubbleSort: bubbleSort.py
	python bubbleSort.py

heapSort: heapSort.py
	python heapSort.py

heapSortVariant: heapSortVariant.py
	python heapSortVariant.py