CC = g++
CFLAGS = -Wall -o
TARGETS = BSTToSortedLinkedList

all: $(TARGETS)

BSTToSortedLinkedList: BSTToSortedLinkedList.cpp BinarySearchTree.h LinkedList.h
	$(CC) $(CFLAGS) solution BSTToSortedLinkedList.cpp

clean:
	rm $(TARGETS)