CC = g++
CFLAGS = -Wall -o
TARGETS = longestOrderedSubarray

all: $(TARGETS)

longestOrderedSubarray: longestOrderedSubarray.cpp
	$(CC) $(CFLAGS) longestOrderedSubarray longestOrderedSubarray.cpp

run: longestOrderedSubarray
	./longestOrderedSubarray

clean:
	rm longestOrderedSubarray