CC = g++
CFLAGS = -Wall -o
TARGETS = SortedLinkedListToBST

all: $(TARGETS)

SortedLinkedListToBST: SortedLinkedListToBST.cpp BinarySearchTree.h LinkedList.h
	$(CC) $(CFLAGS) solution SortedLinkedListToBST.cpp

clean:
	rm $(TARGETS)