TARGETS = bucketSort countingSort radixSortMSD sortWordsLinear

all: $(TARGETS)

bucketSort: bucketSort.py
	python bucketSort.py

countingSort: countingSort.py
	python countingSort.py

radixSortMSD: radixSortMSD.py
	python radixSortMSD.py

sortWordsLinear: sortWordsLinear.py
	python sortWordsLinear.py