CC = g++
CFLAGS = -Wall -o
TARGETS = optimalMeetingPoint

all: $(TARGETS)

optimalMeetingPoint: optimalMeetingPoint.cpp
	$(CC) $(CFLAGS) optimalMeetingPoint optimalMeetingPoint.cpp

run: optimalMeetingPoint
	./optimalMeetingPoint

clean:
	rm optimalMeetingPoint