CC = g++
CFLAGS = -Wall -o
TARGETS = nHorsesBacktracking

all: $(TARGETS)

nHorsesBacktracking: nHorsesBacktracking.cpp
	$(CC) $(CFLAGS) nHorsesBacktracking nHorsesBacktracking.cpp

run: nHorsesBacktracking
	./nHorsesBacktracking

clean:
	rm nHorsesBacktracking