CC = g++
CFLAGS = -Wall -o
TARGETS = sumInTriangles

all: $(TARGETS)

sumInTriangles: sumInTriangles.cpp
	$(CC) $(CFLAGS) sumInTriangles sumInTriangles.cpp

run: sumInTriangles
	./sumInTriangles

clean:
	rm sumInTriangles