CC = g++
CFLAGS = -Wall -o
TARGETS = mergeSortInsertionSortOptimized

all: $(TARGETS)

mergeSortInsertionSortOptimized: mergeSortInsertionSortOptimized.cpp
	$(CC) $(CFLAGS) solution mergeSortInsertionSortOptimized.cpp

clean:
	rm $(TARGETS)